server:
  port: 8084

spring:
  application:
    name: admin-service

  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    service-url:
      # LOCAL
      # defaultZone: http://localhost:8761/eureka

      # DOCKER
      defaultZone: http://eureka-server:8761/eureka

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:

      applicationService:
        failureRateThreshold: 50
        slidingWindowSize: 10
        minimumNumberOfCalls: 5

      documentService:
        failureRateThreshold: 50
        slidingWindowSize: 10
        minimumNumberOfCalls: 5

management:
  tracing:
    sampling:
      probability: 1.0
