server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # AUTH
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            # APPLICATION
            - id: application-service
              uri: lb://APPLICATION-SERVICE
              predicates:
                - Path=/applications/**

            # DOCUMENT
            - id: document-service
              uri: lb://DOCUMENT-SERVICE
              predicates:
                - Path=/documents/**

            # ADMIN
            - id: admin-service
              uri: lb://ADMIN-SERVICE
              predicates:
                - Path=/admin/**

            # SWAGGER ROOT ROUTES
            - id: auth-swagger
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/v3/api-docs
              filters:
                - RewritePath=/auth/v3/api-docs, /v3/api-docs

            - id: application-swagger
              uri: lb://APPLICATION-SERVICE
              predicates:
                - Path=/applications/v3/api-docs
              filters:
                - RewritePath=/applications/v3/api-docs, /v3/api-docs

            - id: document-swagger
              uri: lb://DOCUMENT-SERVICE
              predicates:
                - Path=/documents/v3/api-docs
              filters:
                - RewritePath=/documents/v3/api-docs, /v3/api-docs

            - id: admin-swagger
              uri: lb://ADMIN-SERVICE
              predicates:
                - Path=/admin/v3/api-docs
              filters:
                - RewritePath=/admin/v3/api-docs, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: AUTH
        url: /auth/v3/api-docs
      - name: APPLICATION
        url: /applications/v3/api-docs
      - name: DOCUMENT
        url: /documents/v3/api-docs
      - name: ADMIN
        url: /admin/v3/api-docs

jwt:
  secret: myverysecuresecretkeymyverysecuresecretkey

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
