server:
  port: 8082

spring:
  application:
    name: application-service

  cache:
    type: none   # 🔥 ONLY ADDITION

  datasource:
    # LOCAL
    # url: jdbc:postgresql://localhost:5433/application_service_db

    # DOCKER
    url: jdbc:postgresql://postgres:5432/application_service_db

    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  redis:
    # LOCAL
    # host: localhost

    # DOCKER
    host: redis

    port: 6379

  rabbitmq:
    # LOCAL
    # host: localhost

    # DOCKER
    host: rabbitmq

    port: 5672
    connection-timeout: 5s

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  client:
    service-url:
      # LOCAL
      # defaultZone: http://localhost:8761/eureka

      # DOCKER
      defaultZone: http://eureka-server:8761/eureka


management:
  tracing:
    sampling:
      probability: 1.0

spring:
  zipkin:
    base-url: http://zipkin:9411
