server:
  port: 8082

spring:
  application:
    name: application-service

  cache:
    type: none

  datasource:
    url: jdbc:postgresql://postgres:5432/application_service_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  redis:
    host: redis
    port: 6379

  rabbitmq:
    host: rabbitmq
    port: 5672
    connection-timeout: 5s

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
