server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://postgres:5432/auth-service_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  zipkin:
    base-url: http://zipkin:9411   # ✅ merged

jwt:
  secret: myverysecuresecretkeymyverysecuresecretkey

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
