server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    # LOCAL
    # url: jdbc:postgresql://localhost:5433/auth-service_db

    # DOCKER
    url: jdbc:postgresql://postgres:5432/auth-service_db

    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: myverysecuresecretkeymyverysecuresecretkey

eureka:
  client:
    service-url:
      # LOCAL
      # defaultZone: http://localhost:8761/eureka/

      # DOCKER
      defaultZone: http://eureka-server:8761/eureka/
