server:
  port: 8083

spring:
  application:
    name: document-service

  datasource:
    url: jdbc:postgresql://localhost:5433/document_service_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
