server:
  port: 8083

spring:
  application:
    name: document-service

  datasource:
    url: jdbc:postgresql://postgres:5432/document_service_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: rabbitmq
    port: 5672

  zipkin:
    base-url: http://zipkin:9411   # ✅ merged

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
